name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_nodes:
    path: ../
  gap: ^3.0.1
  uuid: ^4.5.1
  file_picker: ^10.2.4
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  benchmark_harness: ^2.3.1

flutter:
  uses-material-design: true
  shaders:
    - packages/fl_nodes/shaders/grid.frag
