name: fl_nodes_example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0
license: MIT

resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fl_nodes:
    path: ../../packages/fl_nodes

  gap: ^3.0.1
  uuid: ^4.5.1
  file_picker: ^10.3.2
  flutter_context_menu: ^0.4.1
  http: ^1.5.0
  intl: any
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  shaders:
    - packages/fl_nodes_core/shaders/grid.frag
